### PR TITLE
[examples] Add an IR example

### PR DESCRIPTION
**Pull request by ghost**
I tried to port an IR example from Agda but I'm not sure if it actually works yet so I'll just put this here for now in case someone wants to play around with it.

### CODE REVIEW

**Comment by jonsterling** [comment]
Nice, this looks fun! I wonder if it works...

**Comment by jonsterling** [comment]
If you don't mind put this into a "work in progress" folder, then we should just do this kind of thing on master directly...

**Comment by ghost** [comment]
Yeah, I suspect there are some bugs. I've fixed a few already just from going back over it again. I haven't used the recursion stuff before though so I'm not sure what to expect but in principle it seems like this approach should work to some degree.

**Comment by ghost** [comment]
Sure, we can do that. I'll create a new directory and merge it.

**Comment by jonsterling** [comment]
I haven't actually used the `fix` operator yet (Vincent added it recently); in the past I have always just defined the Y combinator myself... I'll be curious to see if the rules we have for `fix` suffice for general use, or if we need to add more.

**Comment by jonsterling** [comment]
@freebroccolo great! I like the idea of doing exploratory JonPRL developments on master, since when I make breaking changes, I can be sure to bring all known developments up to date without causing churn for contributors...

**Pull request merged**
