### PR TITLE
Custom resources

### LINKED ISSUE #209: User Defined Resources
It would be interesting if JonPRL allowed users to define their own resources. Especially since they can be used with the new `resource` tactic.

Possible syntax:

```
 Resource foo.
 Resource foo += { .... }.
```

The idea being that a resource must be declared before its first usage and error in any other case.

### PR DESCRIPTION
**Pull request by jozefg**
This adds support for custom resources, it closes #209. This is a little complicated because we have to track the declared resources so that it's a parse failure to use an undefined resource.

### CODE REVIEW

**Comment by jonsterling** [comment]
Thanks! This turned out to be a little more work than I expected, but looks reasonable!

The only change I would request is to have the vernacular say `Declare Resource name` instead of `Declare name`.

**Comment by jozefg** [comment]
@jonsterling Sounds good! I can't make parcom believe in keywords with whitespace in them though, would `DeclareResource` work?

**Comment by jonsterling** [comment]
Ah! In that case, let's leave it as is for now.

**Comment by jozefg** [comment]
@jonsterling I noticed we could also just do `reserved "Declare" >> reserved "Resource"` which has the same effect :)

**Comment by jonsterling** [comment]
:+1: !

**Pull request merged**
