### PR TITLE
ApproxExtEq & Image Type

### PR DESCRIPTION
**Pull request by vrahli**
Added the ApproxExtEq rule and for that added the image type, which we use to define
the squash operator.

### CODE REVIEW

**Comment by jonsterling** [comment]
Out of curiosity, what is the advantage of using the image type to define squash rather than the set type?

**Comment by vrahli** [comment]
I feel that it's more direct.  Using the image type squash(T) is defined as
Image(T,\x.Ax), and using the set type, it's defined as {True|T}, where
True is really something like Ax = Ax in Base or Ax <= Ax or 0 = 0 in Int...
Also, the set type could potentially be defined in terms of the image type:
{x : T | P(X)} = Image(x:T \* P(x), \x.fst(x)).  If you use snd, you get the
union type.  But, that's something we haven't done yet in Nuprl, because
right now that would require us to prove extra wf lemmas when using the
set type.

On Fri, Jul 24, 2015 at 12:32 AM, Jonathan Sterling <
notifications@github.com> wrote:

> Out of curiosity, what is the advantage of using the image type to define
> squash rather than the set type?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jonsterling/JonPRL/pull/144#issuecomment-124326234.

## 

http://www.cs.cornell.edu/~rahli/

**Comment by jonsterling** [comment]
That makes sense...

One practical concern I have with using the image type to define squash by default is that it is a little more difficult to prove that something is a member. That is, for some member `M`, I have to show that `M = F(N)` in order to inhabit the type `Image(A; F)`. Is this analysis correct?

**Comment by vrahli** [comment]
That's correct.  In the case of squash(T)=Image(T,\x.Ax), to prove that u
in squash(T),
it's enough to prove that u ~ (\x.Ax) t for some t in T, i.e., that u ~
Ax.  Therefore
to unsquash a conclusion, you can either use a lemmas to that effect but
you'll
then have to prove a well-formedness lemma, or you can write a tactic that
asserts T, you get two branches and in the second branch, you get a t in T
and you can then use the witness (\x.Ax) t and finish off that branch using
the
ImageMemberEquality rule.

I don't think using the image type in that instance is going to be an issue
but
I can change it's definition to use the set type if you want.  Let me know.

On Fri, Jul 24, 2015 at 10:42 AM, Jonathan Sterling <
notifications@github.com> wrote:

> That makes sense...
> 
> One practical concern I have with using the image type to define squash by
> default is that it is a little more difficult to prove that something is a
> member. That is, for some member M, I have to show that M = F(N) in order
> to inhabit the type Image(A; F). Is this analysis correct?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jonsterling/JonPRL/pull/144#issuecomment-124545359.

## 

http://www.cs.cornell.edu/~rahli/

**Comment by jonsterling** [comment]
@vrahli OK, that makes sense. In order to write such a tactic, we will probably need Danny's PR #147, after which we may write:

```
Tactic squash-intro {
  @{ [ |- squash(A)] => 
        assert [A]; 
        focus 1 #{
          @{ [H : A |- _] => 
                witness [lam(_.<>) H];
                unfold <squash member>;
                image-mem-eq;
                auto
           }
        }
    }
}.

Theorem squash-test : [squash(unit * unit)] {
  squash-intro; auto
}.
```

**Comment by jonsterling** [comment]
@vrahli Thank you very much for this contribution! Having the image type is very exciting.

**Pull request merged**
