### PR TITLE
Use unification in subst rules

### PR DESCRIPTION
**Pull request by jonsterling**
Depends on https://github.com/jozefg/sml-abt-unify/pull/2

### CODE REVIEW

**Comment by jozefg** [comment]
Nice!! This will be super helpful :)

**Comment by jonsterling** [comment]
@jozefg So it was not (!!!) fun to implement `BHyp`, but it seems to work thanks to your unification machinery...

**Comment by jozefg** [comment]
Ah but that's super nifty, that'll let us do something like Coq's `eapply; auto` pattern quite nicely it would seem (if I'm reading this right).

**Comment by jonsterling** [comment]
I'm going to merge this now to avoid it going stale, but I anticipate that there may still be unencountered bugs in `bhyp`, if only due to the complexity of the code; however, whatever goes wrong there cannot affect soundness, so I think it is fine to merge.

**Pull request merged**
