### PR TITLE
Atoms [WIP]

### PR DESCRIPTION
**Pull request by jonsterling**
This is a preliminary attempt at #29, but I want to wait until Bob and Mark Bickford and I have discussed Nuprl's atoms, to make sure that this is the right way to go about it. In particular, Bob and I are uncertain about "unguessable atoms" / "unhideable tokens", and what that means in practice.

### CODE REVIEW

**Comment by david-christiansen** [comment]
If I've understood right, atoms are like Lisp symbols, right?

**Comment by jonsterling** [comment]
@david-christiansen Yes, they are basically the same thing as symbols in Lisp if I understand them correctly.

I spoke at length with Mark Bickford this morning about atoms in Nuprl and have resolved Bob and my confusion. The confusing thing was that in Allen's semantics for atoms, the thing that was being discussed was _not_ atoms as implemented in Nuprl, but "unguessable atoms", which are a separate (but related) notion.

For the moment, we don't have any need for unguessable atoms, and so the naïve implementation in this stale PR will work fine for our purposes.

**Comment by david-christiansen** [comment]
So unguessable atoms would be something analogous to a hygiene system?

**Comment by jonsterling** [comment]
@david-christiansen Maybe... I'm not familiar enough with hygiene to say. 

The main thrust of the "unguessable" stuff is that you must always be able to take a sequent and perform any permutation or substitution of its unguessable atoms and have it remain evident. An example of something that is not permitted, then, would be a definition like `X =def= %welp` where `%welp` is an unguessable atom. Unguessable atoms cannot appear on the rhs of a definition without having come from the left as a parameter.

**Comment by david-christiansen** [comment]
Ok, that's not what I'd guessed it would be.

**Pull request closed without merging**
