### PR TITLE
Fixed small_step to understand neutral terms

### PR DESCRIPTION
**Pull request by jozefg**
There's still a question in my mind as to what to do binders. Howe would say we should try to step under them and I'm inclined to do the same. The relevant line would be

```
  | x \ e => x \ step e
```

This is safe as far as I know :+1:

### CODE REVIEW

**Comment by jonsterling** [comment]
Hmm, maybe we should step under the binder! Let's try it out.

**Comment by jozefg** [comment]
So Howe would say that x.e ~ x.e' if e ~ e' for an arbitrary `x`. This is what we use `step` for in practice so it make sense there but it's a little strange for a semantics. Harumph.

**Comment by jonsterling** [comment]
Why is that weird?

**Comment by jozefg** [comment]
I suppose we don't step under a canonical operator so maybe this is permissible. We still don't step the bodies of lambdas for example.. Does this ever even come up in a well formed term?

**Comment by jonsterling** [comment]
What about `spread`?

**Comment by jozefg** [comment]
`spread` will eval its first argument and then beta contract. Otherwise it's stuck. There's no way to step the body of the "continuation" like thing.

**Comment by jozefg** [comment]
Currently if two terms step the the same canonical form and have different (but bisimilar bodies) you'd just assert the bisimilarity, prove it, and then rewrite and use `creflexivity`. So that gives us Howe's relation for terms that terminate.

**Comment by jonsterling** [comment]
Ah, right... So probably what we have already suffices.

**Comment by jozefg** [comment]
Though that doesn't quite hold water if we have for example

```
 λx.fst(<x, x>) ~ λx.x
```

Because we can't posit the necessary bisimilarity because the term is open and pain.

**Comment by jonsterling** [comment]
Hmm, good point. That's not great...

**Comment by jozefg** [comment]
We could add a rule

```
  x : base >> e ~ e' 
  ------------------------
         x.e ~ x.e'
```

**Comment by jonsterling** [comment]
The conclusion is not well-formed, though...

**Comment by jozefg** [comment]
Damn it.. What does NuPRL do again?

**Comment by jonsterling** [comment]
50 or 60 rules

**Comment by jozefg** [comment]
:sob:

**Comment by jonsterling** [comment]
Howe probably justifies us to define it generically over all abts though right?

**Comment by jozefg** [comment]
That's true. Perhaps that's the right approach, generalize this to work over terms which bind variables.

**Comment by jonsterling** [comment]
Right; we could have a single rule that generated as many subgoals as there are subterms, expressing the binding structure through context extension `H , x : Base >> ...`.

**Comment by jonsterling** [comment]
This looks reasonable... Is it ready to merge?

**Comment by jozefg** [comment]
This code is really tricky, a careful proof reading and some more tests would be helpful I think.

**Comment by jonsterling** [comment]
OK; I'll give it a careful look-through.

**Comment by jonsterling** [comment]
OK, I've tried it out and read through the code, and it looks reasonable. (I actually think the rule you added is not so bad)

**Pull request merged**
