### PR TITLE
Add argument information to list-tactics

### PR DESCRIPTION
**Pull request by jozefg**
Now --list-tactics has a small specification of what arguments tactics can take. Not full blown manuals or anything but in a similar spirit to giving arities for operators. Also fixed a typo in operator.sml

### CODE REVIEW

**Comment by jozefg** [comment]
Oh also the old information can be completely recovered by just looking at the first word of each line, useful for syntax highlighting and such.

**Comment by jonsterling** [comment]
Thanks! We'll have to check with @david-christiansen to see about whether this jives with what he's using that output for.

EDIT: Ah, as you say, we can just pick out the first word. I'll wait until we can coordinate the change with the emacs mode.

**Comment by david-christiansen** [comment]
You can follow the example of the operator reader if you want to improve the Emacs mode already. Otherwise I'll hopefully get to it before ECOOP.

**Comment by david-christiansen** [comment]
This works in Emacs now. Merge away!

The summaries (everything after the space) are shown in the documentation at the bottom of the screen.

**Comment by jonsterling** [comment]
Okeydoke! Thanks @jozefg & @david-christiansen

**Pull request merged**
