### PR TITLE
Void

### PR DESCRIPTION
**Pull request by vrahli**
Defined void as Ax <= Bot

### CODE REVIEW

**Comment by jonsterling** [comment]
This looks great, thanks @vrahli!

Could you add some documentation to the signature about `AssumeHasValue`? A statement of the rule in nuprl notation as a comment above `val AssumeHasValue...` would suffice. Thanks!

By the way, I made a few changes, so be sure to run:

```
git pull --rebase
git submodule update --init --recursive
```

before making changes

**Comment by vrahli** [comment]
When I run git pull --rebase, I get

  There is no tracking information for the current branch.
  Please specify which branch you want to rebase against.

Should I run git pull --rebase origin master, or something like that?

On Sat, Aug 15, 2015 at 5:43 PM, Jonathan Sterling <notifications@github.com

> wrote:
> 
> This looks great, thanks @vrahli https://github.com/vrahli!
> 
> Could you add some documentation to the signature about AssumeHasValue? A
> statement of the rule in nuprl notation as a comment above val
> AssumeHasValue... would suffice. Thanks!
> 
> By the way, I made a few changes, so be sure to run:
> 
> git pull --rebase
> git submodule update --init --recursive
> ``
> 
> before making changes
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jonsterling/JonPRL/pull/191#issuecomment-131395198.

## 

http://www.cs.cornell.edu/~rahli/

**Comment by jonsterling** [comment]
Try

```
git pull --rebase origin void
```

Best,
Jon

**Comment by vrahli** [comment]
Okay, I've added some comments.

On Sat, Aug 15, 2015 at 6:22 PM, Jonathan Sterling <notifications@github.com

> wrote:
> 
> Try
> 
> git pull --rebase origin void
> 
> Best,
> Jon
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/jonsterling/JonPRL/pull/191#issuecomment-131397899.

## 

http://www.cs.cornell.edu/~rahli/

**Comment by jonsterling** [comment]
Great, thank you! I'll merge this shortly. Very cool change.

**Pull request merged**
